/* Демо полосного раннера (Subway Surfers-стиль): 3 дорожки,
   свайп вверх/вниз меняет полосу, препятствия на полосах, магнит и буст. */
module.exports = {
  genre: 'platformer',
  meta: { title: 'Lanes Runner' },
  theme: {
    accent: '#ffd75e',
    bgTop: '#3a2a5e', bgBottom: '#120a24',
    font: "'Segoe UI', system-ui, sans-serif",
    labels: { over: 'ВРЕЗАЛСЯ', again: 'Тап — заново', scoreUnit: 'метров', hint: 'Свайп ↑↓ — смена полосы' },
  },
  rules: { mode: 'untimed' },
  platformer: {
    tileSize: 16, viewTilesX: 15, mode: 'runner',
    physics: { gravity: 0 },
    player: { w: 0.7, h: 0.9, hp: 1, lives: 1, color: '#ffd75e', weapons: [], abilities: {} },
    runner: {
      speed: 130, ramp: 5, maxSpeed: 280,
      lanes: { rows: [2, 5, 8] },
      chunks: [
        { map: [
          "                ",
          "                ",
          "                ",
          "                ",
          "     C C C      ",
          "                ",
          "                ",
          "                ",
          "                ",
          "                ",
        ] },
        { map: [
          "                ",
          "        #       ",
          "   C            ",
          "                ",
          "        #       ",
          "                ",
          "                ",
          "     C          ",
          "        #       ",
          "                ",
        ] },
        { map: [
          "                ",
          "   #      C     ",
          "                ",
          "                ",
          "   #   M        ",
          "                ",
          "                ",
          "          C     ",
          "   #      B     ",
          "                ",
        ], minM: 25 },
        { map: [
          "                ",
          "     #    #     ",
          "                ",
          "       C        ",
          "  #        #    ",
          "                ",
          "       C        ",
          "                ",
          "     #    #     ",
          "                ",
        ], minM: 50 },
      ],
    },
    legend: {
      '#': { tile: true, solid: true, color: '#8a5a9e' },
      'C': { pickup: 'coin', value: 5, color: '#ffe08a' },
      'M': { pickup: 'magnet', dur: 8, color: '#e06bd0' },
      'B': { pickup: 'boost', dur: 3, color: '#7ce07c' },
    },
  },
};
