# Asset packer for Hungry Kitchen -> games/hungry-kitchen.assets.js
# Food icons are downscaled to 128x128 (PNG with alpha); board (webp) and
# background (jpg) are embedded as-is. ASCII-only on purpose (PS 5.1 mangles
# non-BOM Cyrillic source). Human-readable config with RU labels lives in
# games/hungry-kitchen.config.js and requires the generated assets module.
# Run:  powershell -ExecutionPolicy Bypass -File tools\pack-kitchen-config.ps1
Add-Type -AssemblyName System.Drawing

$dir = 'D:\Sharky\For games\icons\Food'
$out = 'D:\Sharky\game-engine\games\hungry-kitchen.assets.js'
$ICON = 128

function Resize-PngB64($path, $size) {
  $src = [System.Drawing.Image]::FromFile($path)
  $bmp = New-Object System.Drawing.Bitmap($size, $size)
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
  $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
  $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
  $g.Clear([System.Drawing.Color]::Transparent)
  $g.DrawImage($src, 0, 0, $size, $size)
  $ms = New-Object System.IO.MemoryStream
  $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
  $b64 = [Convert]::ToBase64String($ms.ToArray())
  $ms.Dispose(); $g.Dispose(); $bmp.Dispose(); $src.Dispose()
  return 'data:image/png;base64,' + $b64
}
function Raw-B64($path, $mime) {
  return "data:$mime;base64," + [Convert]::ToBase64String([IO.File]::ReadAllBytes($path))
}

$assets = [ordered]@{}
$foods = @()
Get-ChildItem $dir -Filter *.png -File | Where-Object { $_.Name -notlike '*copy*' } | Sort-Object Name | ForEach-Object {
  $key = ($_.BaseName -replace '_Icon', '')
  $assets[$key] = Resize-PngB64 $_.FullName $ICON
  $foods += $key
}
$assets['deck'] = Raw-B64 (Join-Path $dir 'deck.webp') 'image/webp'
$assets['background'] = Raw-B64 (Join-Path $dir 'background.jpg') 'image/jpeg'

$json = $assets | ConvertTo-Json -Depth 4 -Compress
$body = "/* AUTOGENERATED by tools/pack-kitchen-config.ps1 - do not edit. */`r`nmodule.exports = $json;`r`n"
[IO.File]::WriteAllText($out, $body, (New-Object System.Text.UTF8Encoding($false)))
$kb = [math]::Round((Get-Item $out).Length / 1KB, 1)
Write-Output ("OK: $out  foods=$($foods.Count)  assets=$($assets.Count)  size=${kb}KB")
Write-Output ("foods: " + ($foods -join ', '))
