# Generic PixelLab rotation packer.
# Reads a JSON manifest [{k,id,dir,mode}] and writes an assets.js (module.exports={name:dataUrl}).
#   dir  = rotation direction (east for side platformers, south for top-down shmups)
#   mode = 'bottom' (feet-anchored square, platformers) | 'center' (shmup) | 'raw'
# Usage: powershell -ExecutionPolicy Bypass -File tools\pack-px.ps1 <manifest.json> <out.js>
param([string]$manifestPath, [string]$outFile)
Add-Type -AssemblyName System.Drawing

$PROJ = '6a405a9b-fa75-4e82-9b84-e39943e65050'
$B = "https://backblaze.pixellab.ai/file/pixellab-characters/$PROJ"
$tmp = Join-Path $env:TEMP 'px-frames'
New-Item -ItemType Directory -Force -Path $tmp | Out-Null

function Get-Bbox($bmp) {
  $minX = $bmp.Width; $minY = $bmp.Height; $maxX = -1; $maxY = -1
  for ($y = 0; $y -lt $bmp.Height; $y++) {
    for ($x = 0; $x -lt $bmp.Width; $x++) {
      if ($bmp.GetPixel($x, $y).A -gt 20) {
        if ($x -lt $minX) { $minX = $x }; if ($x -gt $maxX) { $maxX = $x }
        if ($y -lt $minY) { $minY = $y }; if ($y -gt $maxY) { $maxY = $y }
      }
    }
  }
  return @($minX, $minY, $maxX, $maxY)
}

$items = Get-Content $manifestPath -Raw | ConvertFrom-Json
$assets = [ordered]@{}
foreach ($it in $items) {
  $url = "$B/$($it.id)/rotations/$($it.dir).png"
  $f = Join-Path $tmp ($it.k + '.png')
  try { Invoke-WebRequest -Uri $url -OutFile $f -UseBasicParsing -ErrorAction Stop | Out-Null }
  catch { Write-Output ("SKIP {0}: download failed" -f $it.k); continue }
  $src = New-Object System.Drawing.Bitmap($f)
  if ($it.mode -eq 'raw') {
    $assets[$it.k] = 'data:image/png;base64,' + [Convert]::ToBase64String([IO.File]::ReadAllBytes($f))
    $src.Dispose(); Write-Output ("raw {0}" -f $it.k); continue
  }
  $bb = Get-Bbox $src
  if ($bb[2] -lt 0) { Write-Output ("SKIP {0}: empty" -f $it.k); $src.Dispose(); continue }
  $cw = $bb[2] - $bb[0] + 1; $chh = $bb[3] - $bb[1] + 1
  $side = [Math]::Max($cw, $chh)
  $dst = New-Object System.Drawing.Bitmap($side, $side)
  $gr = [System.Drawing.Graphics]::FromImage($dst)
  $gr.Clear([System.Drawing.Color]::Transparent)
  $dx = [int](($side - $cw) / 2)
  $dy = if ($it.mode -eq 'center') { [int](($side - $chh) / 2) } else { $side - $chh }
  $gr.DrawImage($src,
    (New-Object System.Drawing.Rectangle($dx, $dy, $cw, $chh)),
    (New-Object System.Drawing.Rectangle($bb[0], $bb[1], $cw, $chh)),
    [System.Drawing.GraphicsUnit]::Pixel)
  $ms = New-Object System.IO.MemoryStream
  $dst.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
  $assets[$it.k] = 'data:image/png;base64,' + [Convert]::ToBase64String($ms.ToArray())
  $ms.Dispose(); $gr.Dispose(); $dst.Dispose(); $src.Dispose()
  Write-Output ("ok {0}: {1}x{2} -> {3}" -f $it.k, $cw, $chh, $side)
}

$json = $assets | ConvertTo-Json -Compress
$body = "/* AUTOGENERATED by tools/pack-px.ps1 - do not edit. */`r`nmodule.exports = $json;`r`n"
[IO.File]::WriteAllText($outFile, $body, (New-Object System.Text.UTF8Encoding($false)))
$kb = [math]::Round((Get-Item $outFile).Length / 1KB, 1)
Write-Output ("WROTE $outFile keys=$($assets.Count) size=${kb}KB")
