# pack-xiangqi.ps1 - download PixelLab map objects, normalize piece sprites,
# emit games/xiangqi.px.js (base64 map). ASCII-only strings (PS 5.1 gotcha).
# Usage: powershell -File tools\pack-xiangqi.ps1 -Manifest tools\px-xiangqi\manifest.json
param([string]$Manifest = "tools\px-xiangqi\manifest.json")

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent $PSScriptRoot
$dir = Join-Path $root 'tools\px-xiangqi'
New-Item -ItemType Directory -Force $dir | Out-Null
$items = Get-Content (Join-Path $root $Manifest) -Raw | ConvertFrom-Json

function Normalize-Piece([string]$inPath, [string]$outPath, [int]$canvas) {
    $src = [System.Drawing.Bitmap]::new($inPath)
    try {
        # bbox by alpha > 15
        $minX = $src.Width; $minY = $src.Height; $maxX = -1; $maxY = -1
        $rect = [System.Drawing.Rectangle]::new(0, 0, $src.Width, $src.Height)
        $data = $src.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        $stride = $data.Stride
        $bytes = New-Object byte[] ($stride * $src.Height)
        [System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $bytes, 0, $bytes.Length)
        $src.UnlockBits($data)
        for ($y = 0; $y -lt $src.Height; $y++) {
            for ($x = 0; $x -lt $src.Width; $x++) {
                $a = $bytes[$y * $stride + $x * 4 + 3]
                if ($a -gt 15) {
                    if ($x -lt $minX) { $minX = $x }; if ($x -gt $maxX) { $maxX = $x }
                    if ($y -lt $minY) { $minY = $y }; if ($y -gt $maxY) { $maxY = $y }
                }
            }
        }
        if ($maxX -lt 0) { throw "empty image: $inPath" }
        $bw = $maxX - $minX + 1; $bh = $maxY - $minY + 1
        # paste bottom-centered: bottom edge at canvas-4
        $dst = [System.Drawing.Bitmap]::new($canvas, $canvas)
        $g = [System.Drawing.Graphics]::FromImage($dst)
        $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::NearestNeighbor
        $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::Half
        $dx = [int](($canvas - $bw) / 2); $dy = $canvas - 4 - $bh
        if ($dy -lt 0) { $dy = 0 }
        $g.DrawImage($src, [System.Drawing.Rectangle]::new($dx, $dy, $bw, $bh),
            [System.Drawing.Rectangle]::new($minX, $minY, $bw, $bh), [System.Drawing.GraphicsUnit]::Pixel)
        $g.Dispose()
        $dst.Save($outPath, [System.Drawing.Imaging.ImageFormat]::Png)
        $dst.Dispose()
        Write-Output ("  {0}: bbox {1}x{2} -> {3}x{3}" -f (Split-Path -Leaf $outPath), $bw, $bh, $canvas)
    } finally { $src.Dispose() }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// generated by tools/pack-xiangqi.ps1 - PixelLab sprites (base64 PNG)')
[void]$sb.AppendLine('module.exports = {')
foreach ($it in $items) {
    $raw = Join-Path $dir ($it.k + '_raw.png')
    $fin = Join-Path $dir ($it.k + '.png')
    if (-not (Test-Path $raw)) {
        Invoke-WebRequest -Uri ("https://api.pixellab.ai/mcp/map-objects/{0}/download" -f $it.id) -OutFile $raw -UseBasicParsing
    }
    if ($it.norm) { Normalize-Piece $raw $fin 64 } else { Copy-Item $raw $fin -Force }
    $b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($fin))
    [void]$sb.AppendLine("  $($it.k): '$b64',")
    Write-Output ("packed {0} ({1} b64 chars)" -f $it.k, $b64.Length)
}
[void]$sb.AppendLine('};')
$out = Join-Path $root 'games\xiangqi.px.js'
[IO.File]::WriteAllText($out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Output ("written: {0} ({1} bytes)" -f $out, (Get-Item $out).Length)
